from django.db import models


class ChampionRating(models.Model):
    name = models.CharField(max_length=120)
    rel_rate = models.FloatField()
    games = models.IntegerField()
    winrate = models.FloatField()
    patch = models.CharField(max_length=120)
    role = models.CharField(max_length=120)
    id = models.CharField(max_length=120, primary_key=True)

    def _str_(self):
        return self.id + " " + self.rel_rate


class GameSummarySoloQ(models.Model):
    gameid = models.IntegerField()
    server = models.CharField(max_length=120)
    date = models.DateTimeField()
    patch = models.CharField(max_length=120)
    duration = models.TimeField()
    account = models.CharField(max_length=120)
    role = models.CharField(max_length=120)
    champion = models.CharField(max_length=120)
    side = models.CharField(max_length=120)
    direct_matchup = models.CharField(max_length=120)
    keystone = models.CharField(max_length=120)
    rune1 = models.CharField(max_length=120)
    rune2 = models.CharField(max_length=120)
    rune3 = models.CharField(max_length=120)
    rune4 = models.CharField(max_length=120)
    rune5 = models.CharField(max_length=120)
    rune1var1 = models.CharField(max_length=120)
    rune1var2 = models.CharField(max_length=120)
    rune1var3 = models.CharField(max_length=120)
    rune2var1 = models.CharField(max_length=120)
    rune2var2 = models.CharField(max_length=120)
    rune2var3 = models.CharField(max_length=120)
    rune3var1 = models.CharField(max_length=120)
    rune3var2 = models.CharField(max_length=120)
    rune3var3 = models.CharField(max_length=120)
    rune4var1 = models.CharField(max_length=120)
    rune4var2 = models.CharField(max_length=120)
    rune4var3 = models.CharField(max_length=120)
    rune5var1 = models.CharField(max_length=120)
    rune5var2 = models.CharField(max_length=120)
    rune5var3 = models.CharField(max_length=120)
    item1 = models.CharField(max_length=120)
    item2 = models.CharField(max_length=120)
    item3 = models.CharField(max_length=120)
    item4 = models.CharField(max_length=120)
    item5 = models.CharField(max_length=120)
    item6 = models.CharField(max_length=120)
    boots = models.CharField(max_length=120)
    trinket = models.CharField(max_length=120)
    skill_order1 = models.CharField(max_length=120)
    skill_order2 = models.CharField(max_length=120)
    skill_order3 = models.CharField(max_length=120)
    skill_order4 = models.CharField(max_length=120)
    skill_order5 = models.CharField(max_length=120)
    skill_order6 = models.CharField(max_length=120)
    skill_order7 = models.CharField(max_length=120)
    skill_order8 = models.CharField(max_length=120)
    skill_order9 = models.CharField(max_length=120)
    skill_order10 = models.CharField(max_length=120)
    skill_order11 = models.CharField(max_length=120)
    skill_order12 = models.CharField(max_length=120)
    skill_order13 = models.CharField(max_length=120)
    skill_order14 = models.CharField(max_length=120)
    skill_order15 = models.CharField(max_length=120)
    skill_order16 = models.CharField(max_length=120)
    skill_order17 = models.CharField(max_length=120)
    skill_order18 = models.CharField(max_length=120)
    skill_order19 = models.CharField(max_length=120)
    skill_order20 = models.CharField(max_length=120)
    skill_order21 = models.CharField(max_length=120)
    skill_order22 = models.CharField(max_length=120)
    skill_order23 = models.CharField(max_length=120)
    summoner1 = models.CharField(max_length=120)
    summoner2 = models.CharField(max_length=120)
    ally1 = models.CharField(max_length=120)
    ally2 = models.CharField(max_length=120)
    ally3 = models.CharField(max_length=120)
    ally4 = models.CharField(max_length=120)
    ally5 = models.CharField(max_length=120)
    ennemy1 = models.CharField(max_length=120)
    ennemy2 = models.CharField(max_length=120)
    ennemy3 = models.CharField(max_length=120)
    ennemy4 = models.CharField(max_length=120)
    ennemy5 = models.CharField(max_length=120)
    win = models.BooleanField()
    performance = models.FloatField()
    id = models.CharField(max_length=120, primary_key=True)


class GameSummaryCompetitive(models.Model):
    gameid = models.CharField(max_length=120)
    league = models.CharField(max_length=120)
    date = models.DateTimeField()
    patch = models.CharField(max_length=120)
    duration = models.IntegerField()
    player = models.CharField(max_length=120)
    team1 = models.CharField(max_length=120)
    team2 = models.CharField(max_length=120)
    side = models.CharField(max_length=120)
    role = models.CharField(max_length=120)
    champion = models.CharField(max_length=120)
    keystone = models.CharField(max_length=120)
    rune1 = models.CharField(max_length=120)
    rune2 = models.CharField(max_length=120)
    rune3 = models.CharField(max_length=120)
    rune4 = models.CharField(max_length=120)
    rune5 = models.CharField(max_length=120)
    statrune1 = models.CharField(max_length=120)
    statrune2 = models.CharField(max_length=120)
    statrune3 = models.CharField(max_length=120)
    ally1 = models.CharField(max_length=120)
    ally2 = models.CharField(max_length=120)
    ally3 = models.CharField(max_length=120)
    ally4 = models.CharField(max_length=120)
    ally5 = models.CharField(max_length=120)
    ennemy1 = models.CharField(max_length=120)
    ennemy2 = models.CharField(max_length=120)
    ennemy3 = models.CharField(max_length=120)
    ennemy4 = models.CharField(max_length=120)
    ennemy5 = models.CharField(max_length=120)
    item1 = models.CharField(max_length=120, blank=True)
    item2 = models.CharField(max_length=120, blank=True)
    item3 = models.CharField(max_length=120, blank=True)
    item4 = models.CharField(max_length=120, blank=True)
    item5 = models.CharField(max_length=120, blank=True)
    item6 = models.CharField(max_length=120, blank=True)
    boots = models.CharField(max_length=120, blank=True)
    trinket = models.CharField(max_length=120, blank=True)
    summoner1 = models.CharField(max_length=120)
    summoner2 = models.CharField(max_length=120)
    relativeKills = models.FloatField(blank=True, null=True)
    relativeDeaths = models.FloatField(blank=True, null=True)
    relativeDamages = models.FloatField(blank=True, null=True)
    relativeDamageTaken = models.FloatField(blank=True, null=True)
    relativeGolds = models.FloatField(blank=True, null=True)
    relativeDmgHealed = models.FloatField(blank=True, null=True)
    relativeDmgMitigated = models.FloatField(blank=True, null=True)
    relativeMinionsKilled = models.FloatField(blank=True, null=True)
    relativeWardsPlaced = models.FloatField(blank=True, null=True)
    relativeWardsKilled = models.FloatField(blank=True, null=True)
    relativeLevel = models.FloatField(blank=True, null=True)
    relativeCCtime = models.FloatField(blank=True, null=True)
    performance = models.FloatField(blank=True, null=True)
    outcome = models.IntegerField()
    day = models.DateField()
    relative_performance = models.FloatField()


class TeamImages(models.Model):
    name = models.CharField(max_length=120)
    logo = models.ImageField()


class ChampionsBuildProperties(models.Model):
    keystones = models.JSONField()
    first_items = models.JSONField()
