# Generated by Django 4.0.1 on 2022-01-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='championrating',
            old_name='rate',
            new_name='rel_rate',
        ),
        migrations.AddField(
            model_name='championrating',
            name='patch',
            field=models.CharField(default=6.1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='championrating',
            name='role',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='championrating',
            name='id',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
    ]
